version: '3.2'
services:
  qdb-server:
    build: qdb-server/
    image: bureau14/qdb-pkg-rpm/qdb-server
    privileged: true
    ports:
      - "2836:2836"

  qdb-api:
    build: qdb-api/
    image: bureau14/qdb-pkg-rpm/qdb-api
    links:
      - "qdb-server"

  qdb-rest:
    build: qdb-rest/
    depends_on:
      - "qdb-api"
    links:
      - "qdb-server"
    image: bureau14/qdb-pkg-rpm/qdb-rest
    ports:
      - "40000:40000"
    privileged: true

  qdb-utils:
    build: qdb-utils/
    depends_on:
      - "qdb-api"
    links:
      - "qdb-server"
      - "qdb-rest"
    image: bureau14/qdb-pkg-rpm/qdb-utils
