agents:
  queue: "default-debian-amd64"

label: "{name}"
key: "{slug}"

commands:
  - bash qdb-api/pack.sh artifacts/*-api.tar.gz
  - bash qdb-server/pack.sh artifacts/*-server.tar.gz
  - bash qdb-utils/pack.sh artifacts/*-utils.tar.gz
  - bash qdb-rest/pack.sh artifacts/*-rest.tar.gz
  - bash qdb-code-signing/rpmsign.sh $(find . -name '*.rpm')

plugins:
  - bureau14/qdb-artifacts#master:
      download:
        clean: true
        projects:
          - project_id: "qdb-pkg-archives"
            files:
              - "*.tar.gz"
            output-dir: artifacts
          - project_id: "qdb-code-signing"
            files:
              - "qdb-code-signing.tar.gz!*"
            output-dir: qdb-code-signing
      upload:
        files:
        - "qdb-*/*.rpm"
      promote: {}
